### ISSUE TITLE
Issues concerning your deployed portfolio

### ISSUE THREAD

**Issue by dazehinn** [dfsalam/portfolio#10]
# Hello @dfsalam 👋 

### Great work you've done on your portfolio. The following are worth commending 👍 
* correct use of github flow ✔️ 
* portfolio matches with Figma template ✔️ 
* transitions included in your portfolio ✔️ 
* great comments in the `html` file ✔️ 

### However, here are some suggestions that could improve your portfolio ♻️ 

* For the sake of screen readers you could wrap your nav-items inside  `li` tags since they are related
* The link in the navbar will be better if it led to the actual section on your portfolio
* one of the transitions in your "works" section actually takes a lot of space while the others have little transitions. Please look into this.
* Please include an animation in your portfolio 
* Please update the live demo link in your README to be the link to the deployed site.

**Comment by dfsalam** [comment]
### Thank you for your feedback, I will work on your suggestions to improve the project. 🚀
